using System.Collections.Concurrent;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CodoMetis.TypeKit.ValueObjects;

/// <summary>
/// Reads value objects from JSON the application stored itself, such as an event store or a
/// document column, <b>without applying their rules</b>.
/// </summary>
/// <remarks>
/// <para>
/// The generated JSON converter applies a validated value object's <c>Create</c>, which is right
/// for input and wrong for stored JSON: a rule added later would make documents written earlier
/// unreadable. This is the JSON counterpart of <see cref="IValueObjectMaterializer{TSelf,T}"/>.
/// </para>
/// <para>
/// Register it on the <see cref="JsonSerializerOptions"/> of the store only:
/// <c>storeOptions.Converters.Add(new StoredJsonConverterFactory());</c>. A converter in the options
/// takes precedence over the type's <c>[JsonConverter]</c>. It is the generated converter itself,
/// in a mode only this factory can create, so documents are read in exactly the format they were
/// written in, dictionary keys included.
/// </para>
/// <para>
/// <b>Never register it on options that read input:</b> a request body, a message from another
/// system, anything a user supplied. Input goes through <c>Create</c>.
/// </para>
/// <para>
/// A value object whose converter has no materializing mode, because it was generated by an earlier
/// version, is left to its own converter, which validates.
/// </para>
/// <para>
/// Trimming and Native AOT: the mode is reached through <see cref="IStoredJsonConverterSource"/>,
/// which the generated converter implements, and the converter is created through the constructor
/// the value object's <c>[JsonConverter]</c> already keeps. An earlier version looked up a private
/// constructor by reflection, which the trimmer removed, so under Native AOT the factory found no
/// materializing mode and stored JSON was validated after all (measured 2026-09-27).
/// </para>
/// </remarks>
public sealed class StoredJsonConverterFactory : JsonConverterFactory
{
    private static readonly ConcurrentDictionary<Type, IStoredJsonConverterSource?> Sources = new();

    /// <inheritdoc/>
    public override bool CanConvert(Type typeToConvert) => Source(typeToConvert) is not null;

    /// <inheritdoc/>
    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options) =>
        (Source(typeToConvert) ?? throw new NotSupportedException($"{typeToConvert} has no generated JSON converter with a materializing mode."))
           .CreateStoredJsonConverter(this);

    /// <summary>
    /// The generated converter named by the value object's <c>[JsonConverter]</c>, when it has a
    /// materializing mode: recognised by <see cref="IStoredJsonConverterSource"/>, never by name.
    /// </summary>
    private static IStoredJsonConverterSource? Source(Type type) =>
        Sources.GetOrAdd(type, static candidate =>
            candidate.GetCustomAttribute<JsonConverterAttribute>(inherit: false)?.ConverterType is { } converterType
         && typeof(IStoredJsonConverterSource).IsAssignableFrom(converterType)
                ? (IStoredJsonConverterSource)Activator.CreateInstance(converterType)!
                : null);
}
