using System.Collections.Concurrent;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace CodoMetis.TypeKit.ValueObjects;

/// <summary>
/// Reads value objects from JSON the application stored itself, such as an event store or a
/// document column, <b>without applying their rules</b>.
/// </summary>
/// <remarks>
/// <para>
/// The generated JSON converter applies a validated value object's <c>Create</c>, which is right
/// for input and wrong for stored JSON: a rule added later would make documents written earlier
/// unreadable. This is the JSON counterpart of <see cref="IValueObjectMaterializer{TSelf,T}"/>.
/// </para>
/// <para>
/// Register it on the <see cref="JsonSerializerOptions"/> of the store only:
/// <c>storeOptions.Converters.Add(new StoredJsonConverterFactory());</c>. A converter in the options
/// takes precedence over the type's <c>[JsonConverter]</c>. It is the generated converter itself,
/// in a mode only this factory can create, so documents are read in exactly the format they were
/// written in, dictionary keys included.
/// </para>
/// <para>
/// <b>Never register it on options that read input:</b> a request body, a message from another
/// system, anything a user supplied. Input goes through <c>Create</c>.
/// </para>
/// <para>
/// A value object whose converter has no materializing mode, because it was generated by an earlier
/// version, is left to its own converter, which validates.
/// </para>
/// </remarks>
public sealed class StoredJsonConverterFactory : JsonConverterFactory
{
    private static readonly ConcurrentDictionary<Type, ConstructorInfo?> MaterializingConstructors = new();

    /// <inheritdoc/>
    public override bool CanConvert(Type typeToConvert) => MaterializingConstructor(typeToConvert) is not null;

    /// <inheritdoc/>
    public override JsonConverter CreateConverter(Type typeToConvert, JsonSerializerOptions options) =>
        (JsonConverter)(MaterializingConstructor(typeToConvert) ?? throw new NotSupportedException($"{typeToConvert} has no generated JSON converter with a materializing mode."))
           .Invoke([true]);

    /// <summary>
    /// The generated converter's private <c>(bool materialize)</c> constructor, for a value object
    /// (recognised by <see cref="IValueObject{TValueObject,T}"/>, never by name).
    /// </summary>
    private static ConstructorInfo? MaterializingConstructor(Type type) =>
        MaterializingConstructors.GetOrAdd(type, static candidate =>
            candidate.GetInterfaces().Any(i => i.IsGenericType && i.GetGenericTypeDefinition() == typeof(IValueObject<,>))
         && candidate.GetCustomAttribute<JsonConverterAttribute>()?.ConverterType is { } converterType
                ? converterType.GetConstructor(BindingFlags.NonPublic | BindingFlags.Instance, [typeof(bool)])
                : null);
}
