using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Testing;

namespace CodoMetis.TypeKit.Analyzers.Tests;

/// <summary>
/// Every rule in generated code: reported where the code maps to a <c>.razor</c> or <c>.cshtml</c>
/// file, and nowhere else.
/// </summary>
/// <remarks>
/// <para>
/// The C# the Razor compiler generates is generated code, which the rules skipped, so
/// <c>@code { OrderId _id = default; }</c> compiled without CMTK0001. The generated file here has
/// what Razor's has: an auto-generated header, a <c>.g.cs</c> name, <c>#line</c> directives back to
/// the markup around the user's code, and <c>#line hidden</c> around its own scaffolding.
/// </para>
/// <para>
/// Each rule's trigger appears three times in it: under <c>#line "Component.razor"</c>, which is
/// reported; under <c>#line hidden</c>, which is not; and outside any mapping, which is not either.
/// That last one is EF Core's compiled model calling <c>Materialize</c> (CMTK0004), and every
/// source-generated serializer. <c>Component</c> is also declared in a file of the user's, so the
/// member rules see a class that is not generated as a whole.
/// </para>
/// </remarks>
public sealed class GeneratedCodeTests
{
    private const string Usings =
        """
        using System;
        using System.Collections.Generic;
        using System.Linq;
        using System.Runtime.CompilerServices;
        using System.Threading.Tasks;
        using CodoMetis.TypeKit;
        using CodoMetis.TypeKit.ValueObjects;

        """;

    private const string Subjects =
        Usings +
        """
        public enum Fault { Refused }

        public readonly struct Plain : IValue<int> { public int Value => 0; }

        public readonly struct Other : IValue<int> { public int Value => 0; }

        public readonly struct Validated : IValidatedValue<Validated, string, Fault>
        {
            public static Result<Validated, Fault> Create(string value) => Result<Validated, Fault>.Error(Fault.Refused);

            public static Validated FromKnownGood(string value, [CallerArgumentExpression(nameof(value))] string? expression = null) => Create(value).Match(v => v, _ => throw new ArgumentException(expression));
        }

        public sealed class Service
        {
            public Result<int, Fault> Load() => 1;
        }

        public partial class Component { }

        """;

    /// <summary>
    /// The generated file. <c>$</c> in a trigger becomes a distinct suffix per copy, and only the copy
    /// under the mapping to the markup keeps its <c>{|#0:…|}</c> location.
    /// </summary>
    private static string Generated(string trigger) =>
        "// <auto-generated/>\n" + Usings +
        $$"""
          public partial class Component
          {
          #line 7 "Components/Component.razor"
              {{trigger.Replace("$", "Mapped")}}
          #line default
          #line hidden
              {{Unmarked(trigger).Replace("$", "Hidden")}}
          #line default
              {{Unmarked(trigger).Replace("$", "Unmapped")}}
          }
          """;

    private static string Unmarked(string trigger) => trigger.Replace("{|#0:", "").Replace("|}", "");

    private static Task Verify<TAnalyzer>(string trigger, string id, DiagnosticSeverity severity, string subjects = Subjects)
        where TAnalyzer : DiagnosticAnalyzer, new()
    {
        var test = new AnalyzerTest<TAnalyzer>(subjects);
        test.TestState.Sources.Add(("Component.razor.g.cs", Generated(trigger)));
        test.TestState.AdditionalReferences.AddRange(RealEntityFrameworkCore.References);
        test.ExpectedDiagnostics.Add(new DiagnosticResult(id, severity).WithLocation(0));
        return test.RunAsync(TestContext.Current.CancellationToken);
    }

    [Fact]
    public Task CMTK0001_reports_in_markup_only() =>
        Verify<ForbiddenDefaultInitializationAnalyzer>("private Plain _$ = {|#0:default|};", "CMTK0001", DiagnosticSeverity.Error);

    [Fact]
    public Task CMTK0002_reports_in_markup_only() =>
        Verify<ValueObjectWithoutGeneratorsAnalyzer>("public readonly struct {|#0:Id$|} : IValue<int> { }", "CMTK0002", DiagnosticSeverity.Error, Usings + "public partial class Component { }");

    [Fact]
    public Task CMTK0003_reports_in_markup_only() =>
        Verify<IgnoredOutcomeAnalyzer>("private void Run$(Service service) { {|#0:service.Load()|}; }", "CMTK0003", DiagnosticSeverity.Warning);

    [Fact]
    public Task CMTK0004_reports_in_markup_only() =>
        Verify<MaterializeOutsidePersistenceAnalyzer>(
            "private static T Rebuild$<T>(int value) where T : IValueObjectMaterializer<T, int> => {|#0:T.Materialize(value)|};", "CMTK0004", DiagnosticSeverity.Error);

    [Fact]
    public Task CMTK0005_reports_in_markup_only() =>
        Verify<DefaultFilledCollectionAnalyzer>("private Plain[] Slots$(int count) => {|#0:new Plain[count]|};", "CMTK0005", DiagnosticSeverity.Warning);

    [Fact]
    public Task CMTK0006_reports_in_markup_only() =>
        Verify<UnassignedNoDefaultMemberAnalyzer>("public Plain {|#0:Id$|} { get; set; }", "CMTK0006", DiagnosticSeverity.Warning);

    [Fact]
    public Task CMTK0007_reports_in_markup_only() =>
        Verify<KnownGoodFromCallerAnalyzer>("private Validated Of$(string input) => Validated.FromKnownGood({|#0:input|});", "CMTK0007", DiagnosticSeverity.Info);

    [Fact]
    public Task CMTK0008_reports_in_markup_only() =>
        Verify<MixedValueComparisonAnalyzer>("private bool Same$(Plain plain, Other other) => {|#0:plain.Value == other.Value|};", "CMTK0008", DiagnosticSeverity.Warning);

    /// <summary>A Razor view compiles to generated code too, mapped to its <c>.cshtml</c>.</summary>
    [Fact]
    public Task A_cshtml_mapping_counts_as_markup() =>
        new AnalyzerTest<ForbiddenDefaultInitializationAnalyzer>(Subjects)
        {
            TestState =
            {
                Sources =
                {
                    ("Views_Home_Index_cshtml.g.cs",
                     Usings +
                     """
                     // <auto-generated/>
                     public sealed class IndexView
                     {
                         public void Execute()
                         {
                     #line 3 "Views/Home/Index.cshtml"
                             var id = {|#0:default(Plain)|};
                     #line default
                         }
                     }
                     """),
                },
            },
            ExpectedDiagnostics = { new DiagnosticResult("CMTK0001", DiagnosticSeverity.Error).WithLocation(0) },
        }.RunAsync(TestContext.Current.CancellationToken);

    /// <summary>
    /// Code under <c>#line hidden</c> in the user's own file, and before its first <c>#line</c>, is
    /// code the user does not see, which Roslyn kept quiet for analyzers that skip generated code, and
    /// still is. A member rule reports at the member's declaration, which the analysis context does
    /// not judge, so the rule has to.
    /// </summary>
    [Fact]
    public Task A_hidden_member_of_a_user_class_stays_silent() =>
        new AnalyzerTest<UnassignedNoDefaultMemberAnalyzer>(
            Subjects +
            """
            #line default
            public sealed class Woven
            {
            #line hidden
                public Plain Hidden { get; set; }
            #line default
                public Plain {|#0:Shown|} { get; set; }
            }

            public sealed partial class Split
            {
                public Plain {|#1:Shown|} { get; set; }
            }
            """)
        {
            TestState =
            {
                Sources =
                {
                    ("Split.cs",
                     """
                     public sealed partial class Split
                     {
                         public Plain BeforeTheFirstDirective { get; set; }
                     #line hidden
                         public Plain Hidden { get; set; }
                     #line default
                     }
                     """),
                },
            },
            ExpectedDiagnostics =
            {
                new DiagnosticResult("CMTK0006", DiagnosticSeverity.Warning).WithLocation(0),
                new DiagnosticResult("CMTK0006", DiagnosticSeverity.Warning).WithLocation(1),
            },
        }.RunAsync(TestContext.Current.CancellationToken);

    /// <summary>
    /// A file is generated by its header alone, or by its name alone, as Roslyn decides it; a
    /// <c>#line</c> to a file that is not markup does not make generated code reportable.
    /// </summary>
    [Fact]
    public Task Generated_code_that_does_not_map_to_markup_stays_silent() =>
        new AnalyzerTest<ForbiddenDefaultInitializationAnalyzer>(Subjects)
        {
            TestState =
            {
                Sources =
                {
                    ("HeaderOnly.cs", "// <auto-generated/>\npublic static class HeaderOnly { public static Plain Make() => default; }"),
                    ("NameOnly.g.cs", "public static class NameOnly { public static Plain Make() => default; }"),
                    ("Mapped.g.cs", "// <auto-generated/>\npublic static class MappedElsewhere {\n#line 3 \"Model.cs\"\n public static Plain Make() => default;\n#line default\n}"),
                },
            },
        }.RunAsync(TestContext.Current.CancellationToken);
}
