using System.ComponentModel;
using System.Globalization;
using Metalama.Framework.Aspects;
using Metalama.Framework.Code;
using Metalama.Framework.Code.SyntaxBuilders;

namespace CodoMetis.TypeKit.Generators;

internal sealed partial class ValueObjectTypeConverterAspect
{
    [Template]
    public bool CanConvertFromTemplate(ITypeDescriptorContext? context, Type sourceType) =>
        sourceType == typeof(string) || meta.Base.CanConvertFrom(context, sourceType);

    [Template]
    public bool CanConvertToTemplate(ITypeDescriptorContext? context, Type? destinationType) =>
        destinationType == typeof(string) || meta.Base.CanConvertTo(context, destinationType);

    [Template]
    public object? ConvertFromTemplate(
        ITypeDescriptorContext?  context,
        CultureInfo?             culture,
        object                   value,
        [CompileTime] INamedType valueObjectType
    )
    {
        if (value is string s)
        {
            // Delegates to the IParsable<T> implementation generated by ValueObjectParsableAspect.
            // culture is passed as IFormatProvider; falls back to InvariantCulture when null
            // to match standard TypeConverter conventions.
            IFormatProvider provider;
            // ReSharper disable once ConvertIfStatementToNullCoalescingExpression
            if (culture == null)
            {
                provider = CultureInfo.InvariantCulture;
            }
            else
            {
                provider = culture;
            }

            return ExpressionFactory.Parse(
                $"{ValueObjectTypes.SourceName(valueObjectType)}.Parse(s, provider)",
                valueObjectType,
                false
            ).Value!;
        }

        return meta.Base.ConvertFrom(context, culture, value);
    }

    [Template]
    public object? ConvertToTemplate(
        ITypeDescriptorContext?  context,
        CultureInfo?             culture,
        object?                  value,
        Type                     destinationType,
        [CompileTime] INamedType valueObjectType,
        [CompileTime] INamedType valueType
    )
    {
        if (destinationType == typeof(string) && value is not null)
        {
            // The wrapped value's text, formatted as the generated ToString(format, provider) formats it,
            // with the culture as the provider. Not the value object's own IFormattable: a value object
            // that declares its ToString() has none, and its text (a mask, a display form) is not what
            // configuration, model binding or a ConvertFrom of the result expects.
            IFormatProvider provider;
            // ReSharper disable once ConvertIfStatementToNullCoalescingExpression
            if (culture == null)
            {
                provider = CultureInfo.InvariantCulture;
            }
            else
            {
                provider = culture;
            }

            string typeName = meta.CompileTime(ValueObjectTypes.SourceName(valueObjectType));

            return ExpressionFactory.Parse(
                ValueObjectFormattableAspect.WrappedText(valueType, $"(({typeName})value).Value", "null", "provider"),
                TypeFactory.GetType(SpecialType.String),
                false
            ).Value;
        }

        return meta.Base.ConvertTo(context, culture, value, destinationType);
    }
}
