using System.Text.Json;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Configs;
using BenchmarkDotNet.Running;
using CodoMetis.TypeKit.ValueObjects;
using Vogen;

BenchmarkSwitcher.FromAssembly(typeof(Program).Assembly).Run(args);

// The same three wrapped types, generated by each library with its defaults.
public readonly partial record struct TkOrderId : IValue<Guid>;
public readonly partial record struct TkAmount : IValue<decimal>;
public readonly partial record struct TkWeekday : IValue<DayOfWeek>;

[ValueObject<Guid>] public readonly partial struct VgOrderId;
[ValueObject<decimal>] public readonly partial struct VgAmount;
// Vogen 8.0.7 does not compile [ValueObject<DayOfWeek>] with its defaults: CS0535, its generated
// IConvertible lacks ToString(IFormatProvider?). The enum sort is TypeKit against the raw enum only.

public sealed record RawLine(Guid Id, decimal Amount);
public sealed record TkLine(TkOrderId Id, TkAmount Amount);
public sealed record VgLine(VgOrderId Id, VgAmount Amount);

[MemoryDiagnoser]
[CategoriesColumn]
[GroupBenchmarksBy(BenchmarkLogicalGroupRule.ByCategory)]
public class Comparison
{
    private const int Count = 1_000;

    private static readonly JsonSerializerOptions Options = new(JsonSerializerDefaults.Web);

    private readonly char[] _chars = new char[64];

    private readonly Guid      _guid = Guid.Parse("0199aaaa-bbbb-7ccc-8ddd-eeeeeeeeeeee");
    private readonly TkOrderId _tkId = TkOrderId.From(Guid.Parse("0199aaaa-bbbb-7ccc-8ddd-eeeeeeeeeeee"));
    private readonly VgOrderId _vgId = VgOrderId.From(Guid.Parse("0199aaaa-bbbb-7ccc-8ddd-eeeeeeeeeeee"));

    private readonly DayOfWeek[] _days = new DayOfWeek[Count], _dayScratch = new DayOfWeek[Count];
    private readonly TkWeekday[] _tkDays = new TkWeekday[Count], _tkDayScratch = new TkWeekday[Count];

    private readonly decimal[]  _amounts = new decimal[Count], _amountScratch = new decimal[Count];
    private readonly TkAmount[] _tkAmounts = new TkAmount[Count], _tkAmountScratch = new TkAmount[Count];
    private readonly VgAmount[] _vgAmounts = new VgAmount[Count], _vgAmountScratch = new VgAmount[Count];

    private RawLine _raw = null!;
    private TkLine  _tk  = null!;
    private VgLine  _vg  = null!;
    private string  _json = null!;

    [GlobalSetup]
    public void Setup()
    {
        var random = new Random(42);
        for (var i = 0; i < Count; i++)
        {
            _days[i]    = (DayOfWeek)random.Next(0, 7);
            _tkDays[i]  = TkWeekday.From(_days[i]);
            _amounts[i] = random.Next(0, 1_000_000) / 100m;
            _tkAmounts[i] = TkAmount.From(_amounts[i]);
            _vgAmounts[i] = VgAmount.From(_amounts[i]);
        }

        _raw  = new RawLine(_guid, 12.5m);
        _tk   = new TkLine(_tkId, TkAmount.From(12.5m));
        _vg   = new VgLine(_vgId, VgAmount.From(12.5m));
        _json = JsonSerializer.Serialize(_raw, Options);

        foreach (var (name, json) in new[] { ("TypeKit", JsonSerializer.Serialize(_tk, Options)), ("Vogen", JsonSerializer.Serialize(_vg, Options)) })
            if (json != _json) throw new InvalidOperationException($"{name} writes {json}, the raw types {_json}");
    }

    [Benchmark(Baseline = true), BenchmarkCategory("Format")] public bool Raw_format() => ((ISpanFormattable)_guid).TryFormat(_chars, out _, default, null);
    [Benchmark, BenchmarkCategory("Format")] public bool TypeKit_format() => _tkId.TryFormat(_chars, out _, default, null);
    [Benchmark, BenchmarkCategory("Format")] public bool Vogen_format() => Format(_vgId);

    [Benchmark(Baseline = true), BenchmarkCategory("EnumSort")] public DayOfWeek Raw_enum_sort() { Array.Copy(_days, _dayScratch, Count); Array.Sort(_dayScratch); return _dayScratch[0]; }
    [Benchmark, BenchmarkCategory("EnumSort")] public TkWeekday TypeKit_enum_sort() { Array.Copy(_tkDays, _tkDayScratch, Count); Array.Sort(_tkDayScratch); return _tkDayScratch[0]; }

    [Benchmark(Baseline = true), BenchmarkCategory("DecimalSort")] public decimal Raw_decimal_sort() { Array.Copy(_amounts, _amountScratch, Count); Array.Sort(_amountScratch); return _amountScratch[0]; }
    [Benchmark, BenchmarkCategory("DecimalSort")] public TkAmount TypeKit_decimal_sort() { Array.Copy(_tkAmounts, _tkAmountScratch, Count); Array.Sort(_tkAmountScratch); return _tkAmountScratch[0]; }
    [Benchmark, BenchmarkCategory("DecimalSort")] public VgAmount Vogen_decimal_sort() { Array.Copy(_vgAmounts, _vgAmountScratch, Count); Array.Sort(_vgAmountScratch); return _vgAmountScratch[0]; }

    [Benchmark(Baseline = true), BenchmarkCategory("JsonWrite")] public string Raw_write() => JsonSerializer.Serialize(_raw, Options);
    [Benchmark, BenchmarkCategory("JsonWrite")] public string TypeKit_write() => JsonSerializer.Serialize(_tk, Options);
    [Benchmark, BenchmarkCategory("JsonWrite")] public string Vogen_write() => JsonSerializer.Serialize(_vg, Options);

    [Benchmark(Baseline = true), BenchmarkCategory("JsonRead")] public RawLine? Raw_read() => JsonSerializer.Deserialize<RawLine>(_json, Options);
    [Benchmark, BenchmarkCategory("JsonRead")] public TkLine? TypeKit_read() => JsonSerializer.Deserialize<TkLine>(_json, Options);
    [Benchmark, BenchmarkCategory("JsonRead")] public VgLine? Vogen_read() => JsonSerializer.Deserialize<VgLine>(_json, Options);

    // Through the interface, as a formatter or an interpolation handler calls it, whichever way the
    // library implements it.
    private bool Format<T>(T value) where T : ISpanFormattable => value.TryFormat(_chars, out _, default, null);
}
